### ISSUE TITLE
Adicionar badge de licença

### ISSUE THREAD

**Issue by nymarya** [odufrn/odufrn-api-py#9]
Adicionar badge de licença como a que existe no nosso outro [repositório](https://github.com/odufrn/odufrn-downloader).

> #### Participe do Hacktoberfest!
> Contribua com uma issue com a label `hacktoberfest` e abra um pull request durante o mês de outubro para ganhar os brindes do GitHub! Para se inscrever, acesse https://hacktoberfest.digitalocean.com/register

**Comment by lyrafelipe** [comment]
@nymarya Bom dia!

Vou pegar essa issue para fazer e já abro o Pull Request, tudo bem?

**Comment by nymarya** [comment]
@lyrafelipe Recomendo esperar até amanhã para abrir o PR e participar do Hacktoberfest! :smile:

**Comment by lyrafelipe** [comment]
@nymarya Obrigado pela dica!

Fiquei só an dúvida se já não está contando visto que o mesmo aparece como progress na minha conta. :thinking:
